-- DDL for Orbital Guard Database

-- 1. SATELLITES Table
CREATE TABLE SATELLITES (
    sat_id VARCHAR2(20) PRIMARY KEY,
    sat_name VARCHAR2(100) NOT NULL,
    altitude_km NUMBER(10, 2) CHECK (altitude_km >= 0),
    speed_kmh VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'MAINTENANCE', 'DECOMMISSIONED')),
    signal_quality_pct NUMBER(5, 2) CHECK (signal_quality_pct BETWEEN 0 AND 100)
);

-- 2. DEBRIS Table
CREATE TABLE DEBRIS (
    debris_id VARCHAR2(20) PRIMARY KEY,
    origin_source VARCHAR2(100),
    altitude_km NUMBER(10, 2) CHECK (altitude_km >= 0),
    speed_kmh VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'UNCONTROLLED'
);

-- 3. ALERTS Table
CREATE TABLE ALERTS (
    alert_id VARCHAR2(20) PRIMARY KEY,
    sat_id VARCHAR2(20),
    debris_id VARCHAR2(20),
    risk_level VARCHAR2(20) CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    conjunction_prob NUMBER(10, 8),
    time_to_conjunction VARCHAR2(50),
    alert_status VARCHAR2(20) DEFAULT 'OPEN' CHECK (alert_status IN ('OPEN', 'RESOLVED', 'FALSE_ALARM')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sat FOREIGN KEY (sat_id) REFERENCES SATELLITES(sat_id) ON DELETE CASCADE,
    CONSTRAINT fk_debris FOREIGN KEY (debris_id) REFERENCES DEBRIS(debris_id) ON DELETE CASCADE
);

-- 4. TELEMETRY_LOGS Table
CREATE TABLE TELEMETRY_LOGS (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sat_id VARCHAR2(20),
    log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recorded_altitude NUMBER(10, 2),
    sync_latency_ms NUMBER(8, 2),
    CONSTRAINT fk_telemetry_sat FOREIGN KEY (sat_id) REFERENCES SATELLITES(sat_id) ON DELETE CASCADE
);
